;; Which order
(source gnu)
(source melpa)

(depends-on "ac-nrepl")
(depends-on "ace-jump-mode")
(depends-on "auctex")
(depends-on "auto-complete")
(depends-on "bookmark+")
(depends-on "diminish")
(depends-on "dired+")
(depends-on "dired-details")
(depends-on "elisp-slime-nav")
(depends-on "elpy")
(depends-on "esup")
(depends-on "expand-region")
(depends-on "ghci-completion")
(depends-on "git-commit-mode")
(depends-on "git-gutter")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "haml-mode")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "highlight-cl")
(depends-on "idle-highlight-mode")
(depends-on "ido-ubiquitous")
(depends-on "jump-char")
(depends-on "lein")
(depends-on "less-css-mode")
(depends-on "lexbind-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "minimap")
(depends-on "multiple-cursors")
(depends-on "nrepl")
(depends-on "org")
(depends-on "paredit")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "redshank")
(depends-on "smex")
(depends-on "ssh-config-mode")
(depends-on "twittering-mode")
(depends-on "use-package")
(depends-on "window-number")
(depends-on "yaml-mode")

; (depends-on "dash")
; (depends-on "drag-stuff")
; (depends-on "multiple-cursors")
; (depends-on "popwin")
; (depends-on "s")
; (depends-on "wrap-region")
; (depends-on "yasnippet")
