(add-to-list 'load-path "~/repositories/emacs_init")
(add-to-list 'load-path "~/repositories/emacs_priv")
(require 'ddb-paths)
(require 'ddb-accounts)

(load custom-file 'noerror)

(require 'ddb-interactives)
(require 'ddb-conf)

(load-theme 'zenburn)

(require 'cask "~/external/cask/cask.el")
(cask-initialize "~/repositories/emacs_init")

(setq package-enable-at-startup nil)

(ddb/conf/general-behavior)
(ddb/conf/copy-cut-line-at-point)
(ddb/conf/ask-before-suspend)
(ddb/conf/global-set-keys)
(ddb/conf/external-programs)
(ddb/conf/changelog)
(ddb/conf/latex)

(require 'ddb-temp)

(setq auto-use-package-symbol-string "ddb/%s/%s")
(require 'auto-use-package)

(defvar ido-cur-item nil)
(defvar ido-default-item nil)
(defvar ido-cur-list nil)
(defvar predicate nil)
(defvar inherit-input-method nil)

(auto-use-package ace-jump-mode)
(auto-use-package artbollocks-mode :defer t)
(auto-use-package auto-complete-config)
(auto-use-package bibtex :defer t)
(auto-use-package css-mode)
(auto-use-package dired)
(auto-use-package dired+)
(auto-use-package dired-details)
(auto-use-package eldoc)
(auto-use-package elisp-slime-nav)
(auto-use-package eproject)
(auto-use-package eproject-extras)
(auto-use-package erc-join)
(auto-use-package erc-services)
(auto-use-package expand-region)
(auto-use-package ffap)
(auto-use-package flyspell :defer t)
(auto-use-package git-gutter)
(auto-use-package gnus)
(auto-use-package haskell-mode :defer t)
(auto-use-package helm-descbinds)
(auto-use-package helm-files)
(auto-use-package helm-misc)
(auto-use-package ibuffer)
(auto-use-package ido :defer t)
(auto-use-package ido-ubiquitous)
(auto-use-package less-css-mode)
(auto-use-package lexbind-mode)
(auto-use-package magit)
(auto-use-package magit-blame)
(auto-use-package markdown-mode)
(auto-use-package mu4e :defer t)
(auto-use-package multiple-cursors)
(auto-use-package octave-mod)
(auto-use-package org)
(auto-use-package org-capture)
(auto-use-package org-protocol)
(auto-use-package outshine)
(auto-use-package paredit)
(auto-use-package proced :defer t)
(auto-use-package prog-mode :defer t)
(auto-use-package projectile)
(auto-use-package rainbow-delimiters)
(auto-use-package redshank)
(auto-use-package saveplace)
(auto-use-package smex)
(auto-use-package term-mode :defer t)
(auto-use-package twittering-mode :defer t)
(auto-use-package uniquify)
(auto-use-package window-number)
(auto-use-package yaml-mode)
(auto-use-package yasnippet)
