(add-to-list 'load-path "~/repositories/emacs_init")
(add-to-list 'load-path "~/repositories/emacs_priv")
(require 'ddb-paths)
(require 'ddb-accounts)

(load custom-file 'noerror)

(require 'ddb-interactives)
(require 'ddb-conf)

(load-theme 'zenburn)

(require 'cask "~/external/cask/cask.el")
(setq cask-project-path "~/repositories/emacs_init")
(cask-initialize)

(ddb/conf/general-behavior)
(ddb/conf/copy-cut-line-at-point)
(ddb/conf/ask-before-suspend)
(ddb/conf/global-set-keys)
(ddb/conf/external-programs)

(ddb/conf/proced)
(ddb/conf/saveplace)

(ddb/conf/prog)
(ddb/conf/text)
(ddb/conf/comint)
(ddb/conf/elisp)
(ddb/conf/lexbind)
(ddb/conf/clojure)
(ddb/conf/haskell)
(ddb/conf/python)
(ddb/conf/latex)

(ddb/conf/changelog)
(ddb/conf/ffap-latex)

(require 'ddb-temp)

(setq auto-use-package-symbol-string "ddb/%s/%s")
(add-to-list 'load-path "~/external/use-package/")
(require 'auto-use-package)

(defvar ido-cur-item nil)
(defvar ido-default-item nil)
(defvar ido-cur-list nil)
(defvar predicate nil)
(defvar inherit-input-method nil)

(auto-use-package ace-jump-mode)
(auto-use-package auto-complete-config)
(auto-use-package bibtex :defer t)
(auto-use-package css-mode)
(auto-use-package expand-region)
(auto-use-package git-gutter)
(auto-use-package gnus)
(auto-use-package helm-descbinds)
(auto-use-package helm-files)
(auto-use-package helm-misc)
(auto-use-package html-mode)
(auto-use-package ido)
(auto-use-package ido-ubiquitous)
(auto-use-package javascript-mode)
(auto-use-package less-css-mode)
(auto-use-package magit)
(auto-use-package markdown-mode)
(auto-use-package multiple-cursors)
(auto-use-package octave-mod)
(auto-use-package org)
(auto-use-package org-protocol)
(auto-use-package projectile)
(auto-use-package rainbow-delimiters)
(auto-use-package smex)
(auto-use-package twittering)
(auto-use-package uniquify)
(auto-use-package window-number)
(auto-use-package yaml-mode)
(auto-use-package yasnippet)

(auto-use-package ibuffer)
;; (auto-use-package dired)
;; (auto-use-package dired-details)
;; (auto-use-package dired+)
